"""empty message

Revision ID: 14710db66d97
Revises: 1f60fc515492
Create Date: 2023-12-12 10:09:28.289665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14710db66d97'
down_revision = '1f60fc515492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presence', schema=None) as batch_op:
        batch_op.drop_constraint('fk_presence_student_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_presence_student_id_user'), 'user', ['student_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_school_admin_id_user'), 'user', ['admin_id'], ['id'], ondelete='SET NULL', use_alter=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_school_id_school', type_='foreignkey')
        batch_op.drop_constraint('fk_user_classroom_id_classroom', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_classroom_id_classroom'), 'classroom', ['classroom_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_user_school_id_school'), 'school', ['school_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_school_id_school'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_classroom_id_classroom'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_classroom_id_classroom', 'classroom', ['classroom_id'], ['id'])
        batch_op.create_foreign_key('fk_user_school_id_school', 'school', ['school_id'], ['id'])

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_school_admin_id_user'), type_='foreignkey')

    with op.batch_alter_table('presence', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_presence_student_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_presence_student_id_user', 'user', ['student_id'], ['id'])

    # ### end Alembic commands ###
