"""empty message

Revision ID: 33e5d6f42d67
Revises: 
Create Date: 2023-11-23 22:59:54.642809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e5d6f42d67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], name=op.f('fk_classroom_school_id_school')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classroom'))
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], name=op.f('fk_school_admin_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], name=op.f('fk_user_classroom_id_classroom')),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], name=op.f('fk_user_school_id_school')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('presence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], name=op.f('fk_presence_classroom_id_classroom')),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], name=op.f('fk_presence_school_id_school')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_presence_student_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_presence'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presence')
    op.drop_table('user')
    op.drop_table('school')
    op.drop_table('classroom')
    # ### end Alembic commands ###
